name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/ssh_key
          chmod 600 ~/ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ~/ssh_key

      - name: SSH Into Server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@52.66.81.169 -i ~/ssh_key << 'EOF'
            cd Turborepo-devops && git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
